import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();
const internships = [
  {
    position: "Software Development Intern",
    company_id: "clrfis59e0000ewkl7yosas6s",
    location: "Silicon Valley",
    id: "clrfjn82z0000fijhjim1bmes",
    workingPlace: "On-site",
    fullTime: true,
    description:
      "Join our dynamic software development team to work on cutting-edge projects. This internship provides hands-on experience in coding, debugging, and collaborating with a team of experienced developers. If you are passionate about creating innovative solutions, this is the opportunity for you. We offer a competitive salary range of $2500 - $3500, and we have 3 open positions available. Apply now and be part of our exciting journey! Application deadline: February 15, 2024, 23:59:59 UTC.",
    paid: true,
    payRangeStart: 2500,
    payRangeEnd: 3500,
    openPositions: 3,
    deadline: new Date("2024-02-15T23:59:59Z"),
  },
  {
    position: "UI/UX Design Intern",
    location: "Silicon Valley",
    id: "clrfjn9pk0007fijhr1qblhi4",
    company_id: "clrfis59e0000ewkl7yosas6s",
    workingPlace: "Remote",
    fullTime: true,
    description:
      "Explore the world of user interface and experience design with our creative team. This internship offers the opportunity to work on real projects, collaborate with cross-functional teams, and contribute to the design process. We provide a competitive salary range of $2000 - $3000, and there are 2 open positions available. Join us in shaping the future of user experiences! Application deadline: February 28, 2024, 23:59:59 UTC.",
    paid: true,
    payRangeStart: 2000,
    payRangeEnd: 3000,
    openPositions: 2,
    deadline: new Date("2024-02-28T23:59:59Z"),
  },
  {
    position: "Data Science Intern",
    location: "Silicon Valley",
    id: "clrfjn9ok0005fijhy9l5yrhj",
    workingPlace: "On-site",
    company_id: "clrfis59e0000ewkl7yosas6s",
    fullTime: false,
    description:
      "Gain hands-on experience in data science and analytics in a collaborative environment. As a Data Science Intern, you will have the opportunity to work on real-world projects, analyze large datasets, and contribute to decision-making processes. While this position is unpaid, the knowledge and skills you gain will be invaluable for your future career. We have 1 open position, and the application deadline is March 15, 2024, 23:59:59 UTC.",
    paid: false,
    payRangeStart: null,
    payRangeEnd: null,
    openPositions: 1,
    deadline: new Date("2024-03-15T23:59:59Z"),
  },
  {
    position: "Cybersecurity Intern",
    location: "Silicon Valley",
    id: "clrfjn9pv0008fijhx7ffd7bx",
    company_id: "clrfis59e0000ewkl7yosas6s",
    workingPlace: "On-site",
    fullTime: true,
    description:
      "Contribute to the security of our systems and infrastructure with our cybersecurity team. As a Cybersecurity Intern, you will be involved in identifying and addressing security vulnerabilities, implementing security measures, and participating in security audits. We offer a competitive salary range of $2800 - $3800, and there are 2 open positions available. Enhance your skills in a challenging and rewarding environment! Application deadline: March 1, 2024, 23:59:59 UTC.",
    paid: true,
    payRangeStart: 2800,
    payRangeEnd: 3800,
    openPositions: 2,
    deadline: new Date("2024-03-01T23:59:59Z"),
  },
  {
    position: "Mobile App Development Intern",
    location: "Silicon Valley",
    id: "clrfjnae5001cfijh8nh2xzal",
    company_id: "clrfis59e0000ewkl7yosas6s",
    workingPlace: "Remote",
    fullTime: false,
    description:
      "Learn and contribute to the development of mobile applications for our innovative projects. This internship provides a hands-on experience in mobile app development, allowing you to work on exciting projects from concept to deployment. While this position is unpaid, the knowledge and experience gained will be valuable for your career growth. We have 1 open position, and the application deadline is February 20, 2024, 23:59:59 UTC.",
    paid: false,
    payRangeStart: null,
    payRangeEnd: null,
    openPositions: 1,
    deadline: new Date("2024-02-20T23:59:59Z"),
  },
  {
    position: "Healthcare Research Intern",
    location: "Toronto",
    id: "clrfjn9oc0004fijh28k303zr",
    company_id: "clrfis59e0001ewklk0p63omw",
    workingPlace: "On-site",
    fullTime: true,
    description:
      "Join our healthcare research team to explore innovative solutions for the industry. As a Healthcare Research Intern, you will have the opportunity to work on cutting-edge projects, analyze healthcare trends, and contribute to the advancement of healthcare knowledge. This full-time position offers a competitive salary range of $2200 - $3200, and we have 3 open positions available. Seize this chance to make a meaningful impact! Application deadline: February 25, 2024, 23:59:59 UTC.",
    paid: true,
    payRangeStart: 2200,
    payRangeEnd: 3200,
    openPositions: 3,
    deadline: new Date("2024-02-25T23:59:59Z"),
  },
  {
    position: "Medical Coding Intern",
    id: "clrfjnaa00014fijhxi71xr1b",
    company_id: "clrfis59e0001ewklk0p63omw",
    location: "Toronto",
    workingPlace: "Remote",
    fullTime: true,
    description:
      "Gain practical experience in medical coding and data management. As a Medical Coding Intern, you will work remotely, learning the intricacies of medical coding and contributing to efficient data management processes. This full-time position comes with a competitive salary range of $2000 - $3000, and we have 2 open positions available. Join us in shaping the future of healthcare data! Application deadline: March 5, 2024, 23:59:59 UTC.",
    paid: true,
    payRangeStart: 2000,
    payRangeEnd: 3000,
    openPositions: 2,
    deadline: new Date("2024-03-05T23:59:59Z"),
  },
  {
    position: "Public Health Intern",
    location: "Toronto",
    id: "clrfjnaa00013fijh6njple9p",
    company_id: "clrfis59e0001ewklk0p63omw",
    workingPlace: "On-site",
    fullTime: false,
    description:
      "Contribute to public health initiatives and projects with our dedicated team. As a Public Health Intern, you will have the opportunity to work on-site, collaborating with professionals in the field. While this position is unpaid, the experience gained will be invaluable for your career in public health. We have 1 open position, and the application deadline is March 20, 2024, 23:59:59 UTC.",
    paid: false,
    payRangeStart: null,
    payRangeEnd: null,
    openPositions: 1,
    deadline: new Date("2024-03-20T23:59:59Z"),
  },
  {
    position: "Healthcare IT Intern",
    location: "Toronto",
    id: "clrfjn9nr0003fijh9haypbil",
    workingPlace: "On-site",
    company_id: "clrfis59e0001ewklk0p63omw",
    fullTime: true,
    description:
      "Explore the intersection of healthcare and technology with our IT team. As a Healthcare IT Intern, you will be involved in implementing and maintaining healthcare IT systems, ensuring their efficiency and security. This full-time position offers a competitive salary range of $2400 - $3400, and we have 2 open positions available. Join us in revolutionizing healthcare through technology! Application deadline: March 10, 2024, 23:59:59 UTC.",
    paid: true,
    payRangeStart: 2400,
    payRangeEnd: 3400,
    openPositions: 2,
    deadline: new Date("2024-03-10T23:59:59Z"),
  },
  {
    position: "Healthcare Analytics Intern",
    location: "Toronto",
    id: "clrfjnaas0016fijhw69r9ex8",
    workingPlace: "Remote",
    company_id: "clrfis59e0001ewklk0p63omw",
    fullTime: false,
    description:
      "Dive into healthcare analytics and contribute to data-driven decision-making. As a Healthcare Analytics Intern, you will work remotely, analyzing healthcare data to derive insights and support informed decision-making. While this position is unpaid, the knowledge gained will be invaluable for your career growth. We have 1 open position, and the application deadline is February 28, 2024, 23:59:59 UTC.",
    paid: false,
    payRangeStart: null,
    payRangeEnd: null,
    openPositions: 1,
    deadline: new Date("2024-02-28T23:59:59Z"),
  },
  {
    position: "Renewable Energy Intern",
    location: "Berlin",
    id: "clrfjnaa00015fijhkqmw32rp",
    company_id: "clrfis59e0002ewklv9cassn8",
    workingPlace: "On-site",
    fullTime: true,
    description:
      "Contribute to sustainable energy solutions for a better future. As a Renewable Energy Intern, you will have the opportunity to work on-site, collaborating with experts in the field to develop and implement renewable energy projects. This full-time position offers a competitive salary range of $2500 - $3500, and we have 3 open positions available. Join us in shaping a more sustainable world! Application deadline: February 22, 2024, 23:59:59 UTC.",
    paid: true,
    payRangeStart: 2500,
    payRangeEnd: 3500,
    openPositions: 3,
    deadline: new Date("2024-02-22T23:59:59Z"),
  },
  {
    position: "Environmental Engineering Intern",
    location: "Berlin",
    company_id: "clrfis59e0002ewklv9cassn8",
    workingPlace: "Remote",
    id: "clrfjnadh001bfijhsq4sjf74",
    fullTime: true,
    description:
      "Work on environmental projects and engineering solutions with our team. As an Environmental Engineering Intern, you will have the opportunity to work remotely, contributing to projects that address environmental challenges and promote sustainable solutions. This full-time position comes with a competitive salary range of $2200 - $3200, and we have 2 open positions available. Join us in making a positive impact on the environment! Application deadline: March 5, 2024, 23:59:59 UTC.",
    paid: true,
    payRangeStart: 2200,
    payRangeEnd: 3200,
    openPositions: 2,
    deadline: new Date("2024-03-05T23:59:59Z"),
  },
  {
    position: "Sustainability Research Intern",
    location: "Berlin",
    id: "clrfjn9mk0001fijhyp8doma1",
    company_id: "clrfis59e0002ewklv9cassn8",
    workingPlace: "On-site",
    fullTime: false,
    description:
      "Contribute to sustainability research and development initiatives. As a Sustainability Research Intern, you will have the opportunity to work on-site, participating in research projects that aim to advance sustainable practices. While this position is unpaid, the experience gained will be valuable for your career in sustainability. We have 1 open position, and the application deadline is March 18, 2024, 23:59:59 UTC.",
    paid: false,
    payRangeStart: null,
    payRangeEnd: null,
    openPositions: 1,
    deadline: new Date("2024-03-18T23:59:59Z"),
  },
  {
    position: "Clean Energy Finance Intern",
    location: "Berlin",
    workingPlace: "On-site",
    id: "clrfjn9tk0009fijh4f5e6ue7",
    company_id: "clrfis59e0002ewklv9cassn8",
    fullTime: true,
    description:
      "Explore the financial aspects of clean energy projects with our finance team. As a Clean Energy Finance Intern, you will be involved in analyzing and supporting financial aspects of clean energy initiatives. This full-time position offers a competitive salary range of $2400 - $3400, and we have 2 open positions available. Join us in driving financial solutions for a sustainable future! Application deadline: March 10, 2024, 23:59:59 UTC.",
    paid: true,
    payRangeStart: 2400,
    payRangeEnd: 3400,
    openPositions: 2,
    deadline: new Date("2024-03-10T23:59:59Z"),
  },
  {
    position: "Green Technology Intern",
    location: "Berlin",
    id: "clrfjn9tk000afijhdvkub4sw",
    workingPlace: "Remote",
    company_id: "clrfis59e0002ewklv9cassn8",
    fullTime: false,
    description:
      "Learn and contribute to the development of green technologies for a sustainable future. As a Green Technology Intern, you will have the opportunity to work remotely, gaining hands-on experience in the development of innovative green technologies. While this position is unpaid, the knowledge and skills acquired will be valuable for your career growth. We have 1 open position, and the application deadline is February 28, 2024, 23:59:59 UTC.",
    paid: false,
    payRangeStart: null,
    payRangeEnd: null,
    openPositions: 1,
    deadline: new Date("2024-02-28T23:59:59Z"),
  },
  {
    position: "Fashion Design Intern",
    location: "Paris",
    company_id: "clrfis59e0003ewklfuwmzhpc",
    id: "clrfjn9tk000bfijhyn2dhrh9",
    workingPlace: "On-site",
    fullTime: true,
    description:
      "Join our trendsetting fashion team to work on innovative design projects. As a Fashion Design Intern, you will have the opportunity to contribute to creative and cutting-edge design concepts. This full-time position offers a competitive salary range of $2000 - $3000, and we have 3 open positions available. Join us in shaping the future of fashion! Application deadline: February 20, 2024, 23:59:59 UTC.",
    paid: true,
    payRangeStart: 2000,
    payRangeEnd: 3000,
    openPositions: 3,
    deadline: new Date("2024-02-20T23:59:59Z"),
  },
  {
    position: "Marketing and Branding Intern",
    location: "Paris",
    id: "clrfjn9pa0006fijhrcmwemyc",
    company_id: "clrfis59e0003ewklfuwmzhpc",
    workingPlace: "Remote",
    fullTime: true,
    description:
      "Contribute to marketing and branding strategies for our global fashion brand. As a Marketing and Branding Intern, you will work remotely, collaborating with our creative team to elevate our brand presence. This full-time position comes with a competitive salary range of $2200 - $3200, and we have 2 open positions available. Join us in shaping the identity of our fashion brand! Application deadline: March 01, 2024, 23:59:59 UTC.",
    paid: true,
    payRangeStart: 2200,
    payRangeEnd: 3200,
    openPositions: 2,
    deadline: new Date("2024-03-01T23:59:59Z"),
  },
  {
    position: "Fashion Merchandising Intern",
    location: "Paris",
    company_id: "clrfis59e0003ewklfuwmzhpc",
    id: "clrfjnad80018fijhh6j3gc46",
    workingPlace: "On-site",
    fullTime: false,
    description:
      "Explore the world of fashion merchandising and retail with our team. As a Fashion Merchandising Intern, you will have the opportunity to gain hands-on experience in merchandising and retail operations. While this position is unpaid, the knowledge and skills acquired will be valuable for your career growth. We have 1 open position, and the application deadline is March 15, 2024, 23:59:59 UTC.",
    paid: false,
    payRangeStart: null,
    payRangeEnd: null,
    openPositions: 1,
    deadline: new Date("2024-03-15T23:59:59Z"),
  },
  {
    position: "Fashion Photography Intern",
    location: "Paris",
    id: "clrfjnad10017fijh6djb02ti",
    company_id: "clrfis59e0003ewklfuwmzhpc",
    workingPlace: "On-site",
    fullTime: true,
    description:
      "Capture the essence of fashion through photography and visual storytelling. As a Fashion Photography Intern, you will work on-site, creating visually stunning content that showcases our fashion collections. This full-time position offers a competitive salary range of $2400 - $3400, and we have 2 open positions available. Join us in bringing fashion to life through captivating imagery! Application deadline: March 10, 2024, 23:59:59 UTC.",
    paid: true,
    payRangeStart: 2400,
    payRangeEnd: 3400,
    openPositions: 2,
    deadline: new Date("2024-03-10T23:59:59Z"),
  },
  {
    position: "E-commerce Operations Intern",
    location: "Paris",
    company_id: "clrfis59e0003ewklfuwmzhpc",
    id: "clrfjnad8001afijh916oqudh",
    workingPlace: "Remote",
    fullTime: false,
    description:
      "Learn and contribute to the operations of our fashion e-commerce platform. As an E-commerce Operations Intern, you will work remotely, gaining hands-on experience in the day-to-day operations of our online fashion platform. While this position is unpaid, the knowledge and experience gained will be valuable for your career growth. We have 1 open position, and the application deadline is February 25, 2024, 23:59:59 UTC.",
    paid: false,
    payRangeStart: null,
    payRangeEnd: null,
    openPositions: 1,
    deadline: new Date("2024-02-25T23:59:59Z"),
  },
  {
    company_id: "clrfis59e0004ewklchbalm4o",
    position: "Culinary Arts Intern",
    location: "Rome",
    workingPlace: "On-site",
    fullTime: true,
    id: "clrfjnagk001dfijhe1qf12q4",
    description:
      "Embark on a culinary journey and contribute to creating delicious food experiences. As a Culinary Arts Intern, you will have the opportunity to work on-site, honing your culinary skills and contributing to the creation of delightful food experiences. This full-time position offers a competitive salary range of $2200 - $3200, and we have 3 open positions available. Join us in crafting culinary masterpieces! Application deadline: February 22, 2024, 23:59:59 UTC.",
    paid: true,
    payRangeStart: 2200,
    payRangeEnd: 3200,
    openPositions: 3,
    deadline: new Date("2024-02-22T23:59:59Z"),
  },
  {
    position: "Food Science Research Intern",
    location: "Rome",
    id: "clrfjn9nn0002fijhdvhpj33q",
    company_id: "clrfis59e0004ewklchbalm4o",
    workingPlace: "Remote",
    fullTime: true,
    description:
      "Conduct research in food science and contribute to the innovation of our culinary creations. As a Food Science Research Intern, you will work remotely, exploring the scientific aspects of food and contributing to the development of innovative culinary creations. This full-time position comes with a competitive salary range of $2000 - $3000, and we have 2 open positions available. Join us in pushing the boundaries of culinary science! Application deadline: March 05, 2024, 23:59:59 UTC.",
    paid: true,
    payRangeStart: 2000,
    payRangeEnd: 3000,
    openPositions: 2,
    deadline: new Date("2024-03-05T23:59:59Z"),
  },
  {
    position: "Restaurant Operations Intern",
    id: "clrfjna9r0012fijhfqgci869",
    company_id: "clrfis59e0004ewklchbalm4o",
    location: "Rome",
    workingPlace: "On-site",
    fullTime: false,
    description:
      "Gain practical experience in restaurant operations and management. As a Restaurant Operations Intern, you will have the opportunity to work on-site, learning the ins and outs of restaurant operations and management. While this position is unpaid, the hands-on experience gained will be invaluable for your career growth. We have 1 open position, and the application deadline is March 18, 2024, 23:59:59 UTC.",
    paid: false,
    payRangeStart: null,
    payRangeEnd: null,
    openPositions: 1,
    deadline: new Date("2024-03-18T23:59:59Z"),
  },
  {
    position: "Food Photography Intern",
    id: "clrfjna9b0011fijhrihadx2n",
    company_id: "clrfis59e0004ewklchbalm4o",
    location: "Rome",
    workingPlace: "On-site",
    fullTime: true,
    description:
      "Capture the beauty of our culinary creations through food photography. As a Food Photography Intern, you will work on-site, capturing visually stunning images that showcase the beauty of our culinary creations. This full-time position offers a competitive salary range of $2400 - $3400, and we have 2 open positions available. Join us in visually celebrating the art of food! Application deadline: March 10, 2024, 23:59:59 UTC.",
    paid: true,
    payRangeStart: 2400,
    payRangeEnd: 3400,
    openPositions: 2,
    deadline: new Date("2024-03-10T23:59:59Z"),
  },
  {
    position: "Supply Chain Management Intern",
    location: "Rome",
    company_id: "clrfis59e0004ewklchbalm4o",
    id: "clrfjnad80019fijh6ossgi62",
    workingPlace: "Remote",
    fullTime: false,
    description:
      "Learn and contribute to the efficiency of our food supply chain. As a Supply Chain Management Intern, you will work remotely, gaining insights into the efficient management of our food supply chain. While this position is unpaid, the knowledge and experience acquired will be valuable for your career growth. We have 1 open position, and the application deadline is February 28, 2024, 23:59:59 UTC.",
    paid: false,
    payRangeStart: null,
    payRangeEnd: null,
    openPositions: 1,
    deadline: new Date("2024-02-28T23:59:59Z"),
  },
  {
    company_id: "clrfis59e0005ewkll7ya1yzy",
    position: "Space Exploration Intern",
    id: "clrfjn9ts000cfijhyhxvcbjo",
    location: "Houston",
    workingPlace: "On-site",
    fullTime: true,
    description:
      "Pioneer space exploration and technology advancement with our innovative team. As a Space Exploration Intern, you will have the unique opportunity to work on-site, contributing to cutting-edge projects in space exploration and technology. This full-time position offers a competitive salary range of $3000 - $4000, and we have 3 open positions available. Join us in pushing the boundaries of space exploration! Application deadline: February 20, 2024, 23:59:59 UTC.",
    paid: true,
    payRangeStart: 3000,
    payRangeEnd: 4000,
    openPositions: 3,
    deadline: new Date("2024-02-20T23:59:59Z"),
  },
  {
    position: "Satellite Technology Intern",
    location: "Houston",
    company_id: "clrfis59e0005ewkll7ya1yzy",
    id: "clrfjn9uf000dfijh10uj0cyq",
    workingPlace: "Remote",
    fullTime: true,
    description:
      "Contribute to the development of satellite technology for space missions. As a Satellite Technology Intern, you will work remotely, playing a key role in advancing satellite technology for space exploration. This full-time position comes with a competitive salary range of $2800 - $3800, and we have 2 open positions available. Join us in shaping the future of satellite technology! Application deadline: March 01, 2024, 23:59:59 UTC.",
    paid: true,
    payRangeStart: 2800,
    payRangeEnd: 3800,
    openPositions: 2,
    deadline: new Date("2024-03-01T23:59:59Z"),
  },
  {
    position: "Astronaut Training Intern",
    company_id: "clrfis59e0005ewkll7ya1yzy",
    location: "Houston",
    workingPlace: "On-site",
    id: "clrfjn9uu000efijhfczloizz",
    fullTime: false,
    description:
      "Participate in astronaut training programs and simulations. As an Astronaut Training Intern, you will have the opportunity to participate in on-site astronaut training programs and simulations. While this position is unpaid, the hands-on experience gained will be invaluable for those aspiring to join the world of space exploration. We have 1 open position, and the application deadline is March 15, 2024, 23:59:59 UTC.",
    paid: false,
    payRangeStart: null,
    payRangeEnd: null,
    openPositions: 1,
    deadline: new Date("2024-03-15T23:59:59Z"),
  },
  {
    position: "Spacecraft Design Intern",
    location: "Houston",
    workingPlace: "On-site",
    company_id: "clrfis59e0005ewkll7ya1yzy",
    id: "clrfjn9wx000ffijh6x1743fe",
    fullTime: true,
    description:
      "Contribute to the design and development of spacecraft for future missions. As a Spacecraft Design Intern, you will work on-site, contributing to the design and development of spacecraft for upcoming missions. This full-time position offers a competitive salary range of $3200 - $4200, and we have 2 open positions available. Join us in shaping the future of space exploration! Application deadline: March 10, 2024, 23:59:59 UTC.",
    paid: true,
    payRangeStart: 3200,
    payRangeEnd: 4200,
    openPositions: 2,
    deadline: new Date("2024-03-10T23:59:59Z"),
  },
  {
    position: "Space Data Analysis Intern",
    id: "clrfjn9wx000gfijho98odfqw",
    location: "Houston",
    workingPlace: "Remote",
    company_id: "clrfis59e0005ewkll7ya1yzy",
    fullTime: false,
    description:
      "Analyze space data and contribute to scientific discoveries. As a Space Data Analysis Intern, you will work remotely, analyzing space data and contributing to scientific discoveries. While this position is unpaid, the experience gained will be valuable for your career growth. We have 1 open position, and the application deadline is February 25, 2024, 23:59:59 UTC.",
    paid: false,
    payRangeStart: null,
    payRangeEnd: null,
    openPositions: 1,
    deadline: new Date("2024-02-25T23:59:59Z"),
  },
  {
    position: "EdTech Software Development Intern",
    location: "London",
    id: "clrfjn9wx000hfijhcm7rzqej",
    company_id: "clrfis59e0006ewkl2be9kssz",
    workingPlace: "On-site",
    fullTime: true,
    description:
      "Revolutionize education through innovative software development projects. As an EdTech Software Development Intern, you will work on-site, playing a key role in revolutionizing education through cutting-edge software development projects. This full-time position offers a competitive salary range of $2500 - $3500, and we have 3 open positions available. Join us in shaping the future of education technology! Application deadline: February 22, 2024, 23:59:59 UTC.",
    paid: true,
    payRangeStart: 2500,
    payRangeEnd: 3500,
    openPositions: 3,
    deadline: new Date("2024-02-22T23:59:59Z"),
  },
  {
    position: "Education Research Intern",
    company_id: "clrfis59e0006ewkl2be9kssz",
    id: "clrfjn9x6000ifijh5r2nalee",
    location: "London",
    workingPlace: "Remote",
    fullTime: true,
    description:
      "Conduct research in education and contribute to the improvement of learning methodologies. As an Education Research Intern, you will work remotely, conducting research in education and contributing to the enhancement of learning methodologies. This full-time position comes with a competitive salary range of $2200 - $3200, and we have 2 open positions available. Join us in shaping the future of education research! Application deadline: March 05, 2024, 23:59:59 UTC.",
    paid: true,
    payRangeStart: 2200,
    payRangeEnd: 3200,
    openPositions: 2,
    deadline: new Date("2024-03-05T23:59:59Z"),
  },
  {
    position: "E-learning Content Creation Intern",
    company_id: "clrfis59e0006ewkl2be9kssz",
    id: "clrfjn9y3000jfijh41lv5292",
    location: "London",
    workingPlace: "On-site",
    fullTime: false,
    description:
      "Create engaging e-learning content for educational platforms. As an E-learning Content Creation Intern, you will work on-site, creating engaging e-learning content for educational platforms. While this position is unpaid, the experience gained will be valuable for those passionate about creating impactful educational materials. We have 1 open position, and the application deadline is March 18, 2024, 23:59:59 UTC.",
    paid: false,
    payRangeStart: null,
    payRangeEnd: null,
    openPositions: 1,
    deadline: new Date("2024-03-18T23:59:59Z"),
  },
  {
    position: "Education Technology Support Intern",
    company_id: "clrfis59e0006ewkl2be9kssz",
    id: "clrfjn9yn000kfijhsw8eiy3p",
    location: "London",
    workingPlace: "On-site",
    fullTime: true,
    description:
      "Provide technical support for educational technology tools and platforms. As an Education Technology Support Intern, you will work on-site, providing technical support for educational technology tools and platforms. This full-time position offers a competitive salary range of $2400 - $3400, and we have 2 open positions available. Join us in supporting the seamless integration of technology in education! Application deadline: March 10, 2024, 23:59:59 UTC.",
    paid: true,
    payRangeStart: 2400,
    payRangeEnd: 3400,
    openPositions: 2,
    deadline: new Date("2024-03-10T23:59:59Z"),
  },
  {
    position: "STEM Education Intern",
    id: "clrfjna05000lfijhy7eo31rd",
    company_id: "clrfis59e0006ewkl2be9kssz",
    location: "London",
    workingPlace: "Remote",
    fullTime: false,
    description:
      "Contribute to STEM education initiatives and projects. As a STEM Education Intern, you will work remotely, contributing to STEM education initiatives and projects. While this position is unpaid, the experience gained will be valuable for those passionate about promoting STEM education. We have 1 open position, and the application deadline is February 28, 2024, 23:59:59 UTC.",
    paid: false,
    payRangeStart: null,
    payRangeEnd: null,
    openPositions: 1,
    deadline: new Date("2024-02-28T23:59:59Z"),
  },
  {
    position: "Travel Experience Design Intern",
    company_id: "clrfis59e0007ewkl7udmaxcf",
    location: "Barcelona",
    workingPlace: "On-site",
    id: "clrfjna05000mfijhs9vfn651",
    fullTime: true,
    description:
      "Contribute to creating memorable travel experiences for explorers worldwide. As a Travel Experience Design Intern, you will work on-site, contributing to the creation of memorable travel experiences for explorers worldwide. This full-time position offers a competitive salary range of $2000 - $3000, and we have 3 open positions available. Join us in shaping the future of travel! Application deadline: February 20, 2024, 23:59:59 UTC.",
    paid: true,
    payRangeStart: 2000,
    payRangeEnd: 3000,
    openPositions: 3,
    deadline: new Date("2024-02-20T23:59:59Z"),
  },
  {
    position: "Digital Marketing Intern",
    company_id: "clrfis59e0007ewkl7udmaxcf",
    location: "Barcelona",
    workingPlace: "Remote",
    id: "clrfjna06000nfijhcw8szfqb",
    fullTime: true,
    description:
      "Develop and implement digital marketing strategies for our travel brand. As a Digital Marketing Intern, you will work remotely, playing a key role in developing and implementing digital marketing strategies for our travel brand. This full-time position comes with a competitive salary range of $2200 - $3200, and we have 2 open positions available. Join us in driving the digital presence of our travel brand! Application deadline: March 01, 2024, 23:59:59 UTC.",
    paid: true,
    payRangeStart: 2200,
    payRangeEnd: 3200,
    openPositions: 2,
    deadline: new Date("2024-03-01T23:59:59Z"),
  },
  {
    position: "Hospitality Management Intern",
    company_id: "clrfis59e0007ewkl7udmaxcf",
    location: "Barcelona",
    workingPlace: "On-site",
    id: "clrfjna0i000ofijhgg5w008w",
    fullTime: false,
    description:
      "Gain practical experience in hospitality management within the travel industry. As a Hospitality Management Intern, you will work on-site, gaining practical experience in hospitality management within the travel industry. While this position is unpaid, the hands-on experience gained will be invaluable for those aspiring to work in the hospitality sector. We have 1 open position, and the application deadline is March 15, 2024, 23:59:59 UTC.",
    paid: false,
    payRangeStart: null,
    payRangeEnd: null,
    openPositions: 1,
    deadline: new Date("2024-03-15T23:59:59Z"),
  },
  {
    position: "Travel Photography Intern",
    company_id: "clrfis59e0007ewkl7udmaxcf",
    location: "Barcelona",
    workingPlace: "On-site",
    fullTime: true,
    id: "clrfjna1s000pfijhq7p4vb7c",
    description:
      "Capture the beauty of travel destinations through photography. As a Travel Photography Intern, you will work on-site, capturing the beauty of travel destinations through photography. This full-time position offers a competitive salary range of $2400 - $3400, and we have 2 open positions available. Join us in showcasing the essence of travel! Application deadline: March 10, 2024, 23:59:59 UTC.",
    paid: true,
    payRangeStart: 2400,
    payRangeEnd: 3400,
    openPositions: 2,
    deadline: new Date("2024-03-10T23:59:59Z"),
  },
  {
    position: "Tourism Business Development Intern",
    location: "Barcelona",
    company_id: "clrfis59e0007ewkl7udmaxcf",
    workingPlace: "Remote",
    id: "clrfjna2b000qfijhc4p28vib",
    fullTime: false,
    description:
      "Contribute to business development initiatives in the tourism sector. As a Tourism Business Development Intern, you will work remotely, contributing to business development initiatives in the tourism sector. While this position is unpaid, the experience gained will be valuable for those interested in the business side of the travel industry. We have 1 open position, and the application deadline is February 25, 2024, 23:59:59 UTC.",
    paid: false,
    payRangeStart: null,
    payRangeEnd: null,
    openPositions: 1,
    deadline: new Date("2024-02-25T23:59:59Z"),
  },
  {
    company_id: "clrfis59e0008ewklq37sdgv4",
    position: "Finance Analyst Intern",
    location: "New York",
    id: "clrfjna3e000sfijhzzbalfcw",
    workingPlace: "On-site",
    fullTime: true,
    description:
      "Contribute to financial analysis and decision-making processes within our finance team. As a Finance Analyst Intern, you will work on-site, playing a key role in financial analysis and decision-making processes within our finance team. This full-time position offers a competitive salary range of $2500 - $3500, and we have 3 open positions available. Join us in shaping the financial future! Application deadline: February 22, 2024, 23:59:59 UTC.",
    paid: true,
    payRangeStart: 2500,
    payRangeEnd: 3500,
    openPositions: 3,
    deadline: new Date("2024-02-22T23:59:59Z"),
  },
  {
    position: "Investment Banking Intern",
    id: "clrfjna3e000rfijhqdxk2uqj",
    company_id: "clrfis59e0008ewklq37sdgv4",
    location: "New York",
    workingPlace: "Remote",
    fullTime: true,
    description:
      "Gain experience in investment banking and financial strategy development. As an Investment Banking Intern, you will work remotely, gaining valuable experience in investment banking and financial strategy development. This full-time position offers a competitive salary range of $2800 - $3800, and we have 2 open positions available. Join us in the world of finance and investment! Application deadline: March 05, 2024, 23:59:59 UTC.",
    paid: true,
    payRangeStart: 2800,
    payRangeEnd: 3800,
    openPositions: 2,
    deadline: new Date("2024-03-05T23:59:59Z"),
  },
  {
    position: "Financial Planning Intern",
    location: "New York",
    company_id: "clrfis59e0008ewklq37sdgv4",
    workingPlace: "On-site",
    fullTime: false,
    id: "clrfjna3e000tfijh0pevchx3",
    description:
      "Assist in financial planning and budgeting processes within our finance department. As a Financial Planning Intern, you will work on-site, assisting in financial planning and budgeting processes within our finance department. While this position is unpaid, the hands-on experience gained will be invaluable for those interested in financial planning. We have 1 open position, and the application deadline is March 18, 2024, 23:59:59 UTC.",
    paid: false,
    payRangeStart: null,
    payRangeEnd: null,
    openPositions: 1,
    deadline: new Date("2024-03-18T23:59:59Z"),
  },
  {
    position: "Risk Management Intern",
    location: "New York",
    id: "clrfjna40000ufijhe1jmus6f",
    company_id: "clrfis59e0008ewklq37sdgv4",
    workingPlace: "On-site",
    fullTime: true,
    description:
      "Contribute to risk assessment and management strategies in the financial sector. As a Risk Management Intern, you will work on-site, contributing to risk assessment and management strategies in the financial sector. This full-time position offers a competitive salary range of $2400 - $3400, and we have 2 open positions available. Join us in navigating the world of financial risk! Application deadline: March 10, 2024, 23:59:59 UTC.",
    paid: true,
    payRangeStart: 2400,
    payRangeEnd: 3400,
    openPositions: 2,
    deadline: new Date("2024-03-10T23:59:59Z"),
  },
  {
    position: "Financial Technology Intern",
    location: "New York",
    company_id: "clrfis59e0008ewklq37sdgv4",
    id: "clrfjna5m000vfijhh8nviea4",
    workingPlace: "Remote",
    fullTime: false,
    description:
      "Explore the intersection of finance and technology with our financial tech team. As a Financial Technology Intern, you will work remotely, exploring the intersection of finance and technology with our financial tech team. While this position is unpaid, the experience gained will be valuable for those interested in the evolving field of fintech. We have 1 open position, and the application deadline is February 28, 2024, 23:59:59 UTC.",
    paid: false,
    payRangeStart: null,
    payRangeEnd: null,
    openPositions: 1,
    deadline: new Date("2024-02-28T23:59:59Z"),
  },
  {
    position: "Sports Technology Research Intern",
    id: "clrfjna62000wfijh51zlmpiu",
    location: "Sydney",
    company_id: "clrfis59e0009ewkltd9knel0",
    workingPlace: "On-site",
    fullTime: true,
    description:
      "Contribute to sports technology research projects and innovations. As a Sports Technology Research Intern, you will work on-site, contributing to cutting-edge sports technology research projects and innovations. This full-time position offers a competitive salary range of $2200 - $3200, and we have 3 open positions available. Join us in shaping the future of sports technology! Application deadline: February 25, 2024, 23:59:59 UTC.",
    paid: true,
    payRangeStart: 2200,
    payRangeEnd: 3200,
    openPositions: 3,
    deadline: new Date("2024-02-25T23:59:59Z"),
  },
  {
    position: "Athlete Performance Analysis Intern",
    location: "Sydney",
    id: "clrfjna6m000xfijhibb3jnyy",
    company_id: "clrfis59e0009ewkltd9knel0",
    workingPlace: "Remote",
    fullTime: true,
    description:
      "Analyze and contribute to athlete performance data to enhance athletic capabilities. As an Athlete Performance Analysis Intern, you will work remotely, analyzing and contributing to athlete performance data to enhance athletic capabilities. This full-time position offers a competitive salary range of $2000 - $3000, and we have 2 open positions available. Join us in optimizing athlete performance! Application deadline: March 05, 2024, 23:59:59 UTC.",
    paid: true,
    payRangeStart: 2000,
    payRangeEnd: 3000,
    openPositions: 2,
    deadline: new Date("2024-03-05T23:59:59Z"),
  },
  {
    position: "Sports Equipment Design Intern",
    location: "Sydney",
    id: "clrfjna6m000zfijhr00qjsx3",
    workingPlace: "On-site",
    company_id: "clrfis59e0009ewkltd9knel0",
    fullTime: false,
    description:
      "Work on the design and development of innovative sports equipment. As a Sports Equipment Design Intern, you will work on-site, contributing to the design and development of innovative sports equipment. While this position is unpaid, the hands-on experience gained will be invaluable for those interested in sports equipment design. We have 1 open position, and the application deadline is March 20, 2024, 23:59:59 UTC.",
    paid: false,
    payRangeStart: null,
    payRangeEnd: null,
    openPositions: 1,
    deadline: new Date("2024-03-20T23:59:59Z"),
  },
  {
    position: "Sports Medicine Intern",
    location: "Sydney",
    workingPlace: "On-site",
    company_id: "clrfis59e0009ewkltd9knel0",
    fullTime: true,
    id: "clrfjna6m000yfijhzzr55rkr",
    description:
      "Contribute to sports medicine research and practices within our dynamic team. As a Sports Medicine Intern, you will work on-site, contributing to sports medicine research and practices within our dynamic team. This full-time position offers a competitive salary range of $2400 - $3400, and we have 2 open positions available. Join us in advancing sports medicine! Application deadline: March 10, 2024, 23:59:59 UTC.",
    paid: true,
    payRangeStart: 2400,
    payRangeEnd: 3400,
    openPositions: 2,
    deadline: new Date("2024-03-10T23:59:59Z"),
  },
  {
    position: "Sports Data Analytics Intern",
    id: "clrfjna7b0010fijh9ozku4c4",
    location: "Sydney",
    workingPlace: "Remote",
    company_id: "clrfis59e0009ewkltd9knel0",
    fullTime: false,
    description:
      "Analyze sports data to derive insights for strategic decision-making. As a Sports Data Analytics Intern, you will work remotely, analyzing sports data to derive insights for strategic decision-making. While this position is unpaid, the experience gained will be valuable for those interested in the intersection of sports and data analytics. We have 1 open position, and the application deadline is February 28, 2024, 23:59:59 UTC.",
    paid: false,
    payRangeStart: null,
    payRangeEnd: null,
    openPositions: 1,
    deadline: new Date("2024-02-28T23:59:59Z"),
  },
];

const companies = [
  {
    name: "TechHub",
    description:
      "TechHub is a leading technology company specializing in software development. With a relentless commitment to innovation, we empower businesses to thrive in the digital landscape. Our team of skilled engineers and visionaries collaborate to deliver cutting-edge solutions that redefine industries. From scalable software architectures to robust applications, TechHub is at the forefront of technological advancement. Visit our website at [TechHub](http://www.techhub.com) to explore how we turn ideas into reality.",
    country: "United States",
    headquarters: "Silicon Valley",
    employees: 1000,
    domain: "Technology",
    website: "http://www.techhub.com",
  },
  {
    name: "HealthSolutions",
    description:
      "HealthSolutions is an innovative healthcare solutions provider committed to transforming the way healthcare is delivered. Our mission is to enhance patient outcomes, streamline workflows, and drive efficiency in the healthcare ecosystem. From cutting-edge medical technologies to data-driven insights, HealthSolutions is dedicated to improving lives. Learn more about our impactful solutions by visiting our website at [HealthSolutions](http://www.healthsolutions.com). Join us in shaping the future of healthcare.",
    country: "Canada",
    headquarters: "Toronto",
    employees: 500,
    domain: "Healthcare",
    website: "http://www.healthsolutions.com",
  },
  {
    name: "GreenEnergy Co.",
    description:
      "GreenEnergy Co. is a pioneer in sustainable energy solutions, committed to building a better and greener future. With a focus on renewable resources and eco-friendly technologies, we lead the way in creating energy solutions that minimize environmental impact. Visit our website at [GreenEnergy Co.](http://www.greenenergyco.com) to discover how we harness the power of nature to drive sustainable progress.",
    country: "Germany",
    headquarters: "Berlin",
    employees: 200,
    domain: "Energy",
    website: "http://www.greenenergyco.com",
  },
  {
    name: "FashionVogue",
    description:
      "FashionVogue is a trendsetting fashion company with a global presence, setting the standards for style and creativity. Our passion for design, coupled with a commitment to quality, defines our approach to the world of fashion. From runway to retail, FashionVogue delivers innovative and captivating collections that resonate with diverse audiences. Explore the intersection of art and fashion by visiting our website at [FashionVogue](http://www.fashionvogue.com). Join us in shaping the future of the fashion industry.",
    country: "France",
    headquarters: "Paris",
    employees: 800,
    domain: "Fashion",
    website: "http://www.fashionvogue.com",
  },
  {
    name: "FoodMasters",
    description:
      "FoodMasters are culinary experts dedicated to bringing delightful food experiences to every corner of the world. With a focus on innovation and a deep appreciation for diverse cuisines, we create memorable moments around the dining table. Visit our website at [FoodMasters](http://www.foodmasters.com) to explore our culinary creations and join us on a journey of gastronomic delight.",
    country: "Italy",
    headquarters: "Rome",
    employees: 300,
    domain: "Food",
    website: "http://www.foodmasters.com",
  },
  {
    name: "SpaceTech Innovations",
    description:
      "SpaceTech Innovations is at the forefront of pioneering space exploration and technology advancement. Our team of experts and visionaries push the boundaries of what's possible in space, driving innovation that shapes the future of humanity's presence beyond Earth. Explore the cosmos with us by visiting our website at [SpaceTech Innovations](http://www.spacetechinnovations.com) and join our mission to unlock the mysteries of the universe.",
    country: "United States",
    headquarters: "Houston",
    employees: 1200,
    domain: "Space",
    website: "http://www.spacetechinnovations.com",
  },
  {
    name: "EduTech Solutions",
    description:
      "EduTech Solutions is revolutionizing education through innovative technology. We believe in the power of education to transform lives, and our cutting-edge solutions empower educators and learners alike. Visit our website at [EduTech Solutions](http://www.edutechsolutions.com) to discover how we are shaping the future of learning and knowledge dissemination.",
    country: "United Kingdom",
    headquarters: "London",
    employees: 600,
    domain: "Education",
    website: "http://www.edutechsolutions.com",
  },
  {
    name: "TravelWonders",
    description:
      "TravelWonders is dedicated to creating memorable travel experiences for explorers around the globe. Our curated journeys immerse travelers in diverse cultures, breathtaking landscapes, and unique adventures. Embark on a discovery of the world's wonders by visiting our website at [TravelWonders](http://www.travelwonders.com). Join us in the pursuit of extraordinary travel memories.",
    country: "Spain",
    headquarters: "Barcelona",
    employees: 400,
    domain: "Travel",
    website: "http://www.travelwonders.com",
  },
  {
    name: "FinancialGenius",
    description:
      "FinancialGenius is a leading financial services company providing smart solutions for individuals and businesses. Our expertise spans a range of financial services, from investment strategies to wealth management. Visit our website at [FinancialGenius](http://www.financialgenius.com) to explore how we empower financial success and security.",
    country: "United States",
    headquarters: "New York",
    employees: 900,
    domain: "Finance",
    website: "http://www.financialgenius.com",
  },
  {
    name: "SportsTech Dynamics",
    description:
      "SportsTech Dynamics is dedicated to innovative sports technology that enhances athletic performance. From cutting-edge equipment to data-driven insights, we redefine the possibilities in sports. Visit our website at [SportsTech Dynamics](http://www.sportstechdynamics.com) to explore how we are shaping the future of sports excellence.",
    country: "Australia",
    headquarters: "Sydney",
    employees: 250,
    domain: "Sports",
    website: "http://www.sportstechdynamics.com",
  },
];
// const reviews = [
//   {
//     companyId: "clrfis59e0005ewkll7ya1yzy",
//     title: "Space Exploration Intern",
//     position: "On-site",
//     description:
//       "Pioneer space exploration and technology advancement with our innovative team.",
//     stars: 4,
//     startDate: "2024-02-15T00:00:00Z",
//     endDate: "2024-05-15T00:00:00Z",
//   },
//   {
//     companyId: "clrfis59e0005ewkll7ya1yzy",
//     title: "Satellite Technology Intern",
//     position: "Remote",
//     description:
//       "Contribute to the development of satellite technology for space missions.",
//     stars: 5,
//     startDate: "2024-03-01T00:00:00Z",
//     endDate: "2024-06-01T00:00:00Z",
//   },
//   {
//     companyId: "clrfis59e0005ewkll7ya1yzy",
//     title: "Astronaut Training Intern",
//     position: "On-site",
//     description: "Participate in astronaut training programs and simulations.",
//     stars: 3,
//     startDate: "2024-04-01T00:00:00Z",
//     endDate: "2024-06-30T00:00:00Z",
//   },
//   {
//     companyId: "clrfis59e0005ewkll7ya1yzy",
//     title: "Spacecraft Design Intern",
//     position: "On-site",
//     description:
//       "Contribute to the design and development of spacecraft for future missions.",
//     stars: 4,
//     startDate: "2024-03-15T00:00:00Z",
//     endDate: "2024-06-15T00:00:00Z",
//   },
//   {
//     companyId: "clrfis59e0005ewkll7ya1yzy",
//     title: "Space Data Analysis Intern",
//     position: "Remote",
//     description: "Analyze space data and contribute to scientific discoveries.",
//     stars: 4,
//     startDate: "2024-03-01T00:00:00Z",
//     endDate: "2024-05-01T00:00:00Z",
//   },
//   {
//     companyId: "clrfis59e0006ewkl2be9kssz",
//     title: "EdTech Software Development Intern",
//     position: "On-site",
//     description:
//       "Revolutionize education through innovative software development projects.",
//     stars: 5,
//     startDate: "2024-02-22T00:00:00Z",
//     endDate: "2024-05-22T00:00:00Z",
//   },
//   {
//     companyId: "clrfis59e0006ewkl2be9kssz",
//     title: "Education Research Intern",
//     position: "Remote",
//     description:
//       "Conduct research in education and contribute to the improvement of learning methodologies.",
//     stars: 4,
//     startDate: "2024-03-05T00:00:00Z",
//     endDate: "2024-06-05T00:00:00Z",
//   },
//   {
//     companyId: "clrfis59e0006ewkl2be9kssz",
//     title: "E-learning Content Creation Intern",
//     position: "On-site",
//     description:
//       "Create engaging e-learning content for educational platforms.",
//     stars: 3,
//     startDate: "2024-04-01T00:00:00Z",
//     endDate: "2024-06-30T00:00:00Z",
//   },
//   {
//     companyId: "clrfis59e0006ewkl2be9kssz",
//     title: "Education Technology Support Intern",
//     position: "On-site",
//     description:
//       "Provide technical support for educational technology tools and platforms.",
//     stars: 4,
//     startDate: "2024-03-10T00:00:00Z",
//     endDate: "2024-06-10T00:00:00Z",
//   },
//   {
//     companyId: "clrfis59e0006ewkl2be9kssz",
//     title: "STEM Education Intern",
//     position: "Remote",
//     description: "Contribute to STEM education initiatives and projects.",
//     stars: 3,
//     startDate: "2024-02-28T00:00:00Z",
//     endDate: "2024-05-28T00:00:00Z",
//   },
//   {
//     companyId: "clrfis59e0007ewkl7udmaxcf",
//     title: "Travel Experience Design Intern",
//     position: "On-site",
//     description:
//       "Contribute to creating memorable travel experiences for explorers worldwide.",
//     stars: 4,
//     startDate: "2024-02-20T00:00:00Z",
//     endDate: "2024-05-20T00:00:00Z",
//   },
//   {
//     companyId: "clrfis59e0007ewkl7udmaxcf",
//     title: "Digital Marketing Intern",
//     position: "Remote",
//     description:
//       "Develop and implement digital marketing strategies for our travel brand.",
//     stars: 5,
//     startDate: "2024-03-01T00:00:00Z",
//     endDate: "2024-06-01T00:00:00Z",
//   },
//   {
//     companyId: "clrfis59e0007ewkl7udmaxcf",
//     title: "Hospitality Management Intern",
//     position: "On-site",
//     description:
//       "Gain practical experience in hospitality management within the travel industry.",
//     stars: 3,
//     startDate: "2024-03-15T00:00:00Z",
//     endDate: "2024-06-15T00:00:00Z",
//   },
//   {
//     companyId: "clrfis59e0007ewkl7udmaxcf",
//     title: "Travel Photography Intern",
//     position: "On-site",
//     description:
//       "Capture the beauty of travel destinations through photography.",
//     stars: 4,
//     startDate: "2024-03-10T00:00:00Z",
//     endDate: "2024-06-10T00:00:00Z",
//   },
//   {
//     companyId: "clrfis59e0007ewkl7udmaxcf",
//     title: "Tourism Business Development Intern",
//     position: "Remote",
//     description:
//       "Contribute to business development initiatives in the tourism sector.",
//     stars: 3,
//     startDate: "2024-02-25T00:00:00Z",
//     endDate: "2024-05-25T00:00:00Z",
//   },
//   {
//     companyId: "clrfis59e0008ewklq37sdgv4",
//     title: "Finance Analyst Intern",
//     position: "On-site",
//     description:
//       "Contribute to financial analysis and decision-making processes within our finance team.",
//     stars: 5,
//     startDate: "2024-02-22T00:00:00Z",
//     endDate: "2024-05-22T00:00:00Z",
//   },
//   {
//     companyId: "clrfis59e0008ewklq37sdgv4",
//     title: "Investment Banking Intern",
//     position: "Remote",
//     description:
//       "Gain experience in investment banking and financial strategy development.",
//     stars: 4,
//     startDate: "2024-03-05T00:00:00Z",
//     endDate: "2024-06-05T00:00:00Z",
//   },
//   {
//     companyId: "clrfis59e0008ewklq37sdgv4",
//     title: "Financial Planning Intern",
//     position: "On-site",
//     description:
//       "Assist in financial planning and budgeting processes within our finance department.",
//     stars: 3,
//     startDate: "2024-04-01T00:00:00Z",
//     endDate: "2024-06-30T00:00:00Z",
//   },
//   {
//     companyId: "clrfis59e0008ewklq37sdgv4",
//     title: "Risk Management Intern",
//     position: "On-site",
//     description:
//       "Contribute to risk assessment and management strategies in the financial sector.",
//     stars: 4,
//     startDate: "2024-03-10T00:00:00Z",
//     endDate: "2024-06-10T00:00:00Z",
//   },
//   {
//     companyId: "clrfis59e0008ewklq37sdgv4",
//     title: "Financial Technology Intern",
//     position: "Remote",
//     description:
//       "Explore the intersection of finance and technology with our financial tech team.",
//     stars: 3,
//     startDate: "2024-02-28T00:00:00Z",
//     endDate: "2024-05-28T00:00:00Z",
//   },
//   {
//     companyId: "clrfis59e0009ewkltd9knel0",
//     title: "Sports Technology Research Intern",
//     position: "On-site",
//     description:
//       "Contribute to sports technology research projects and innovations.",
//     stars: 4,
//     startDate: "2024-02-25T00:00:00Z",
//     endDate: "2024-05-25T00:00:00Z",
//   },
//   {
//     companyId: "clrfis59e0009ewkltd9knel0",
//     title: "Athlete Performance Analysis Intern",
//     position: "Remote",
//     description:
//       "Analyze and contribute to athlete performance data to enhance athletic capabilities.",
//     stars: 5,
//     startDate: "2024-03-05T00:00:00Z",
//     endDate: "2024-06-05T00:00:00Z",
//   },
//   {
//     companyId: "clrfis59e0009ewkltd9knel0",
//     title: "Sports Equipment Design Intern",
//     position: "On-site",
//     description:
//       "Work on the design and development of innovative sports equipment.",
//     stars: 3,
//     startDate: "2024-03-20T00:00:00Z",
//     endDate: "2024-06-20T00:00:00Z",
//   },
//   {
//     companyId: "clrfis59e0009ewkltd9knel0",
//     title: "Sports Medicine Intern",
//     position: "On-site",
//     description:
//       "Contribute to sports medicine research and practices within our dynamic team.",
//     stars: 4,
//     startDate: "2024-03-10T00:00:00Z",
//     endDate: "2024-06-10T00:00:00Z",
//   },
//   {
//     companyId: "clrfis59e0009ewkltd9knel0",
//     title: "Sports Data Analytics Intern",
//     position: "Remote",
//     description:
//       "Analyze sports data to derive insights for strategic decision-making.",
//     stars: 3,
//     startDate: "2024-02-28T00:00:00Z",
//     endDate: "2024-05-28T00:00:00Z",
//   },
// ];

const reviews = [
  {
    companyId: "clrfis59e0005ewkll7ya1yzy",
    title: "Space Exploration Intern",
    position: "On-site",
    description:
      "Pioneer space exploration and technology advancement with our innovative team.",
    stars: 4,
    startDate: "2024-02-15T00:00:00Z",
    endDate: "2024-05-15T00:00:00Z",
  },
  {
    companyId: "clrfis59e0005ewkll7ya1yzy",
    title: "Satellite Technology Intern",
    position: "Remote",
    description:
      "Contribute to the development of satellite technology for space missions.",
    stars: 5,
    startDate: "2024-03-01T00:00:00Z",
    endDate: "2024-06-01T00:00:00Z",
  },
  {
    companyId: "clrfis59e0005ewkll7ya1yzy",
    title: "Astronaut Training Intern",
    position: "On-site",
    description: "Participate in astronaut training programs and simulations.",
    stars: 3,
    startDate: "2024-04-01T00:00:00Z",
    endDate: "2024-06-30T00:00:00Z",
  },
  {
    companyId: "clrfis59e0006ewkl2be9kssz",
    title: "EdTech Software Development Intern",
    position: "On-site",
    description:
      "Revolutionize education through innovative software development projects.",
    stars: 5,
    startDate: "2024-02-22T00:00:00Z",
    endDate: "2024-05-22T00:00:00Z",
  },
  {
    companyId: "clrfis59e0006ewkl2be9kssz",
    title: "Education Research Intern",
    position: "Remote",
    description:
      "Conduct research in education and contribute to the improvement of learning methodologies.",
    stars: 4,
    startDate: "2024-03-05T00:00:00Z",
    endDate: "2024-06-05T00:00:00Z",
  },
  {
    companyId: "clrfis59e0006ewkl2be9kssz",
    title: "E-learning Content Creation Intern",
    position: "On-site",
    description:
      "Create engaging e-learning content for educational platforms.",
    stars: 3,
    startDate: "2024-04-01T00:00:00Z",
    endDate: "2024-06-30T00:00:00Z",
  },
  {
    companyId: "clrfis59e0007ewkl7udmaxcf",
    title: "Travel Experience Design Intern",
    position: "On-site",
    description:
      "Contribute to creating memorable travel experiences for explorers worldwide.",
    stars: 4,
    startDate: "2024-02-20T00:00:00Z",
    endDate: "2024-05-20T00:00:00Z",
  },
  {
    companyId: "clrfis59e0007ewkl7udmaxcf",
    title: "Digital Marketing Intern",
    position: "Remote",
    description:
      "Develop and implement digital marketing strategies for our travel brand.",
    stars: 5,
    startDate: "2024-03-01T00:00:00Z",
    endDate: "2024-06-01T00:00:00Z",
  },
  {
    companyId: "clrfis59e0007ewkl7udmaxcf",
    title: "Hospitality Management Intern",
    position: "On-site",
    description:
      "Gain practical experience in hospitality management within the travel industry.",
    stars: 3,
    startDate: "2024-03-15T00:00:00Z",
    endDate: "2024-06-15T00:00:00Z",
  },
  {
    companyId: "clrfis59e0008ewklq37sdgv4",
    title: "Finance Analyst Intern",
    position: "On-site",
    description:
      "Contribute to financial analysis and decision-making processes within our finance team.",
    stars: 5,
    startDate: "2024-02-22T00:00:00Z",
    endDate: "2024-05-22T00:00:00Z",
  },
  {
    companyId: "clrfis59e0008ewklq37sdgv4",
    title: "Investment Banking Intern",
    position: "Remote",
    description:
      "Gain experience in investment banking and financial strategy development.",
    stars: 4,
    startDate: "2024-03-05T00:00:00Z",
    endDate: "2024-06-05T00:00:00Z",
  },
  {
    companyId: "clrfis59e0008ewklq37sdgv4",
    title: "Financial Planning Intern",
    position: "On-site",
    description:
      "Assist in financial planning and budgeting processes within our finance department.",
    stars: 3,
    startDate: "2024-04-01T00:00:00Z",
    endDate: "2024-06-30T00:00:00Z",
  },
  {
    companyId: "clrfis59e0009ewkltd9knel0",
    title: "Sports Technology Research Intern",
    position: "On-site",
    description:
      "Contribute to sports technology research projects and innovations.",
    stars: 4,
    startDate: "2024-02-25T00:00:00Z",
    endDate: "2024-05-25T00:00:00Z",
  },
  {
    companyId: "clrfis59e0009ewkltd9knel0",
    title: "Athlete Performance Analysis Intern",
    position: "Remote",
    description:
      "Analyze and contribute to athlete performance data to enhance athletic capabilities.",
    stars: 5,
    startDate: "2024-03-05T00:00:00Z",
    endDate: "2024-06-05T00:00:00Z",
  },
  {
    companyId: "clrfis59e0009ewkltd9knel0",
    title: "Sports Equipment Design Intern",
    position: "On-site",
    description:
      "Work on the design and development of innovative sports equipment.",
    stars: 3,
    startDate: "2024-03-20T00:00:00Z",
    endDate: "2024-06-20T00:00:00Z",
  },
];
const reviewTech = [
  {
    companyId: "clrfis59e0000ewkl7yosas6s",
    title: "Software Development Intern",
    position: "On-site",
    description:
      "Experience the forefront of software development and contribute to innovative projects.",
    stars: 4,
    startDate: "2024-02-15T00:00:00Z",
    endDate: "2024-05-15T00:00:00Z",
  },
];
async function main() {
  // await prisma.company.updateMany({
  //   data: companies,
  //   where: {
  //     name: {
  //       in: companies.map((c) => c.name),
  //     },
  //   },
  // });
  // for (const company of companies) {
  //   await prisma.company.update({
  //     data: company,
  //     where: {
  //       name: company.name,
  //     },
  //   });
  // }
  // const createInternships = internships.map((internship) => {
  //   return prisma.internship.update({
  //     data: {
  //       ...internship,
  //       company_id: undefined,
  //       Company: {
  //         connect: {
  //           id: internship.company_id,
  //         },
  //       },
  //     },
  //     where: {
  //       id: internship.id,
  //     },
  //   });
  // });
  // await Promise.all(createInternships);

  const createReviews = reviewTech.map((review) => {
    return prisma.review.create({
      data: {
        ...review,
        companyId: undefined,
        Company: {
          connect: {
            id: review.companyId,
          },
        },
      },
    });
  });
  await Promise.all(createReviews);
}
main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
